export type BudgetTier = "$" | "$$" | "$$$";

export interface Attraction {
  id: string;
  name: string;
  city: string;
  country: string;
  description: string;
  image: string;
  rating: number;
  budgetTier: BudgetTier;
  budgetLabel: string;
  bestTime: string;
  /** Exactly three must-see activities, shown in the hover highlights overlay. */
  highlights: [string, string, string];
  funFact: string;
}

export type CountryCode = "US" | "GB" | "FR" | "JP" | "AU" | "BR" | "IN" | "EG" | "IT" | "MX";

export const DEFAULT_COUNTRY: CountryCode = "US";

export const COUNTRY_NAMES: Record<CountryCode, string> = {
  US: "United States",
  GB: "United Kingdom",
  FR: "France",
  JP: "Japan",
  AU: "Australia",
  BR: "Brazil",
  IN: "India",
  EG: "Egypt",
  IT: "Italy",
  MX: "Mexico",
};

type RawAttraction = Omit<Attraction, "image">;

function withImage(raw: RawAttraction): Attraction {
  // CarouselStack renders this into a fixed h-44 (176px) thumbnail inside a
  // max-w-[22rem] (352px) card, up to 6 of which can be mounted at once
  // (current + peek slots). The previous 640x800 request was ~4x more
  // pixels than ever get displayed, downloaded in full for every one of
  // those simultaneously-mounted cards. 480x320 comfortably covers the
  // display size (including device-pixel-ratio 2x) at a fraction of the
  // bytes.
  return { ...raw, image: `https://picsum.photos/seed/${raw.id}/480/320` };
}

const RAW_ATTRACTIONS: Record<CountryCode, RawAttraction[]> = {
  US: [
    {
      id: "us-statue-of-liberty",
      name: "Statue of Liberty",
      city: "New York City",
      country: "United States",
      description: "An iconic copper colossus guarding New York Harbor since 1886.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "$25–45 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Climb to the crown for panoramic harbor views",
        "Ellis Island Immigration Museum ferry combo",
        "Liberty Island sunset photography",
      ],
      funFact: "The statue's copper skin is only as thick as two stacked pennies.",
    },
    {
      id: "us-grand-canyon",
      name: "Grand Canyon",
      city: "Arizona",
      country: "United States",
      description: "A mile-deep canyon carved by the Colorado River over millions of years.",
      rating: 4.9,
      budgetTier: "$",
      budgetLabel: "$20–35 per person",
      bestTime: "Mar–May",
      highlights: [
        "Hike the Bright Angel Trail at sunrise",
        "Watch sunset from Mather Point",
        "Raft the Colorado River through the inner gorge",
      ],
      funFact: "The canyon is so vast it has its own weather patterns and microclimates.",
    },
    {
      id: "us-golden-gate",
      name: "Golden Gate Bridge",
      city: "San Francisco",
      country: "United States",
      description: "A fog-wreathed art deco suspension bridge spanning the bay.",
      rating: 4.8,
      budgetTier: "$",
      budgetLabel: "Free–$15",
      bestTime: "Sep–Oct",
      highlights: [
        "Walk or bike across at sunset",
        "Visit the vista point for classic postcard shots",
        "Explore Fort Point beneath the south tower",
      ],
      funFact: "The bridge's International Orange color was chosen to stand out in fog.",
    },
    {
      id: "us-disney-world",
      name: "Walt Disney World",
      city: "Orlando",
      country: "United States",
      description: "A sprawling theme park resort built around four immersive parks.",
      rating: 4.6,
      budgetTier: "$$$",
      budgetLabel: "$150–250 per person",
      bestTime: "Jan–Mar",
      highlights: [
        "Ride Space Mountain in Magic Kingdom",
        "Watch the nightly fireworks over Cinderella Castle",
        "Sample flavors from around the world at Epcot",
      ],
      funFact: "The resort is roughly the size of San Francisco, with room to spare.",
    },
    {
      id: "us-yellowstone",
      name: "Yellowstone National Park",
      city: "Wyoming",
      country: "United States",
      description: "Geysers, hot springs, and roaming bison across untamed wilderness.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "$35–70 per person",
      bestTime: "Jun–Aug",
      highlights: [
        "Watch Old Faithful erupt on schedule",
        "Spot bison and elk in Lamar Valley",
        "Hike the boardwalks around Grand Prismatic Spring",
      ],
      funFact: "Yellowstone sits atop one of the world's largest active volcanic systems.",
    },
    {
      id: "us-vegas-strip",
      name: "Las Vegas Strip",
      city: "Nevada",
      country: "United States",
      description: "A neon-lit stretch of casinos, shows, and round-the-clock energy.",
      rating: 4.3,
      budgetTier: "$$$",
      budgetLabel: "$100–300 per person",
      bestTime: "Mar–May",
      highlights: [
        "See the Bellagio fountains at night",
        "Catch a headline residency show",
        "Take in the skyline from the High Roller wheel",
      ],
      funFact: "The Strip is technically not within Las Vegas city limits.",
    },
  ],
  GB: [
    {
      id: "gb-tower-of-london",
      name: "Tower of London",
      city: "London",
      country: "United Kingdom",
      description: "A historic fortress guarding centuries of royal history and crown jewels.",
      rating: 4.6,
      budgetTier: "$$",
      budgetLabel: "£25–35 per person",
      bestTime: "May–Sep",
      highlights: [
        "View the Crown Jewels up close",
        "Join a Yeoman Warder guided tour",
        "Spot the resident ravens on the green",
      ],
      funFact: "Legend holds the kingdom will fall if the Tower's ravens ever leave.",
    },
    {
      id: "gb-stonehenge",
      name: "Stonehenge",
      city: "Wiltshire",
      country: "United Kingdom",
      description: "A prehistoric ring of standing stones shrouded in mystery.",
      rating: 4.4,
      budgetTier: "$$",
      budgetLabel: "£20–30 per person",
      bestTime: "Jun–Aug",
      highlights: [
        "Walk the stone circle perimeter path",
        "Visit at summer solstice sunrise",
        "Tour the on-site Neolithic houses exhibit",
      ],
      funFact: "Some of the bluestones were transported nearly 150 miles from Wales.",
    },
    {
      id: "gb-edinburgh-castle",
      name: "Edinburgh Castle",
      city: "Edinburgh",
      country: "United Kingdom",
      description: "A brooding fortress perched above the Scottish capital.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "£18–28 per person",
      bestTime: "Jul–Sep",
      highlights: [
        "Watch the One O'Clock Gun fire",
        "See the Honours of Scotland crown jewels",
        "Wander the Royal Mile below the ramparts",
      ],
      funFact: "The castle sits atop an extinct volcanic plug over 340 million years old.",
    },
    {
      id: "gb-british-museum",
      name: "The British Museum",
      city: "London",
      country: "United Kingdom",
      description: "A vast free collection spanning human history and culture.",
      rating: 4.8,
      budgetTier: "$",
      budgetLabel: "Free (donations welcome)",
      bestTime: "Year-round",
      highlights: [
        "See the Rosetta Stone",
        "Walk beneath the Great Court's glass roof",
        "Visit the Egyptian mummies gallery",
      ],
      funFact: "It was the first national public museum in the world, opening in 1759.",
    },
    {
      id: "gb-lake-district",
      name: "Lake District",
      city: "Cumbria",
      country: "United Kingdom",
      description: "Rolling fells and glassy lakes that inspired generations of poets.",
      rating: 4.7,
      budgetTier: "$",
      budgetLabel: "£10–25 per person",
      bestTime: "May–Sep",
      highlights: [
        "Hike up Scafell Pike, England's highest peak",
        "Take a steamer cruise on Windermere",
        "Visit Beatrix Potter's Hill Top farmhouse",
      ],
      funFact: "The region inspired both Wordsworth's poetry and Potter's Peter Rabbit tales.",
    },
    {
      id: "gb-windsor-castle",
      name: "Windsor Castle",
      city: "Windsor",
      country: "United Kingdom",
      description: "The world's oldest occupied castle, still a working royal residence.",
      rating: 4.6,
      budgetTier: "$$",
      budgetLabel: "£28–35 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Watch the Changing of the Guard",
        "Tour St George's Chapel",
        "See the intricate Queen Mary's Dolls' House",
      ],
      funFact: "It's the longest-occupied palace in Europe, in use for over 900 years.",
    },
  ],
  FR: [
    {
      id: "fr-eiffel-tower",
      name: "Eiffel Tower",
      city: "Paris",
      country: "France",
      description: "An iron lattice icon offering sweeping views over the City of Light.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "€20–40 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Ride the lift to the third-floor summit",
        "Picnic on the Champ de Mars lawn",
        "See the tower sparkle on the hour after dark",
      ],
      funFact: "It was meant to be dismantled after 20 years but was kept for radio transmissions.",
    },
    {
      id: "fr-louvre",
      name: "Louvre Museum",
      city: "Paris",
      country: "France",
      description: "The world's largest art museum, home to the Mona Lisa.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "€17–25 per person",
      bestTime: "Sep–Nov",
      highlights: [
        "See the Mona Lisa in the Salle des États",
        "Explore the Napoleon III apartments",
        "Walk through the glass pyramid entrance at dusk",
      ],
      funFact: "It would take over 100 days to see every piece for just 30 seconds each.",
    },
    {
      id: "fr-versailles",
      name: "Palace of Versailles",
      city: "Versailles",
      country: "France",
      description: "A gilded royal palace surrounded by manicured formal gardens.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "€20–30 per person",
      bestTime: "May–Jun",
      highlights: [
        "Walk the Hall of Mirrors",
        "Stroll the geometric formal gardens",
        "Rent a rowboat on the Grand Canal",
      ],
      funFact: "The gardens alone once required 200,000 flowers to be replanted every year.",
    },
    {
      id: "fr-french-riviera",
      name: "French Riviera",
      city: "Nice",
      country: "France",
      description: "Sun-soaked beaches and glamorous coastal towns along the Mediterranean.",
      rating: 4.6,
      budgetTier: "$$$",
      budgetLabel: "€100–200 per person",
      bestTime: "Jun–Aug",
      highlights: [
        "Sunbathe on Nice's Promenade des Anglais",
        "Wander Old Town Antibes' market streets",
        "People-watch in Monaco's Casino Square",
      ],
      funFact: "Monaco, part of the Riviera's glamour, is smaller than New York's Central Park.",
    },
    {
      id: "fr-mont-saint-michel",
      name: "Mont Saint-Michel",
      city: "Normandy",
      country: "France",
      description: "A tidal island crowned by a medieval abbey rising from the sea.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "€12–20 per person",
      bestTime: "Apr–Sep",
      highlights: [
        "Cross the tidal causeway at low tide",
        "Climb to the abbey's cloister",
        "Watch Europe's fastest tides roll in",
      ],
      funFact: "At high tide, the island can become completely cut off from the mainland.",
    },
    {
      id: "fr-chamonix",
      name: "Chamonix",
      city: "French Alps",
      country: "France",
      description: "A storied alpine town beneath the shadow of Mont Blanc.",
      rating: 4.6,
      budgetTier: "$$$",
      budgetLabel: "€80–150 per person",
      bestTime: "Dec–Mar",
      highlights: [
        "Ride the Aiguille du Midi cable car",
        "Ski the legendary Vallée Blanche off-piste run",
        "Hike to Mer de Glace glacier",
      ],
      funFact: "Chamonix hosted the first-ever Winter Olympics in 1924.",
    },
  ],
  JP: [
    {
      id: "jp-fushimi-inari",
      name: "Fushimi Inari Shrine",
      city: "Kyoto",
      country: "Japan",
      description: "Thousands of vermilion torii gates winding up a sacred mountain.",
      rating: 4.8,
      budgetTier: "$",
      budgetLabel: "Free",
      bestTime: "Oct–Nov",
      highlights: [
        "Walk the full torii gate trail to the summit",
        "Photograph the gates at golden hour",
        "Sample street food at the shrine's base",
      ],
      funFact: "The shrine has an estimated 10,000 torii gates donated by businesses.",
    },
    {
      id: "jp-mount-fuji",
      name: "Mount Fuji",
      city: "Shizuoka",
      country: "Japan",
      description: "Japan's iconic snow-capped volcano and a pilgrimage for climbers.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "¥3,000–6,000 per person",
      bestTime: "Jul–Aug",
      highlights: [
        "Climb during the official July–August season",
        "Watch sunrise from the summit",
        "View the peak reflected in Lake Kawaguchi",
      ],
      funFact: "Mount Fuji last erupted in 1707 and is still classified as active.",
    },
    {
      id: "jp-shibuya-crossing",
      name: "Shibuya Crossing",
      city: "Tokyo",
      country: "Japan",
      description: "The world's busiest pedestrian scramble beneath a wall of neon.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "Free",
      bestTime: "Mar–May",
      highlights: [
        "Cross with the crowd at peak rush hour",
        "View it from above at Shibuya Sky",
        "Snap a photo with the Hachiko statue",
      ],
      funFact: "Up to 3,000 people can cross at once when the lights change.",
    },
    {
      id: "jp-arashiyama-bamboo",
      name: "Arashiyama Bamboo Grove",
      city: "Kyoto",
      country: "Japan",
      description: "Towering bamboo stalks creaking overhead along a quiet path.",
      rating: 4.6,
      budgetTier: "$",
      budgetLabel: "Free–¥500",
      bestTime: "Mar–May",
      highlights: [
        "Walk the main bamboo path at dawn",
        "Visit nearby Tenryu-ji Temple gardens",
        "Ride a rickshaw through the grove",
      ],
      funFact: "The bamboo stalks can grow up to a meter in a single day.",
    },
    {
      id: "jp-osaka-castle",
      name: "Osaka Castle",
      city: "Osaka",
      country: "Japan",
      description: "A five-story castle rebuilt in concrete, ringed by cherry blossoms.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "¥600 per person",
      bestTime: "Mar–Apr",
      highlights: [
        "Tour the castle's history museum",
        "Picnic under cherry blossoms in the park",
        "View the castle illuminated at night",
      ],
      funFact: "The original castle's stone walls include some boulders weighing over 100 tons.",
    },
    {
      id: "jp-okinawa-beaches",
      name: "Okinawa Beaches",
      city: "Okinawa",
      country: "Japan",
      description: "Turquoise subtropical waters fringed by coral reefs.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "¥8,000–15,000 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Snorkel the coral reefs at Cape Maeda",
        "Relax on Emerald Beach in Ocean Expo Park",
        "Try local Okinawan soba",
      ],
      funFact: "Okinawa's waters are home to one of the world's largest whale shark aquariums.",
    },
  ],
  AU: [
    {
      id: "au-sydney-opera-house",
      name: "Sydney Opera House",
      city: "Sydney",
      country: "Australia",
      description: "A sail-shaped icon perched on the edge of Sydney Harbour.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "AU$45–70 per person",
      bestTime: "Sep–Nov",
      highlights: [
        "Take a guided backstage tour",
        "Watch a performance under the shells",
        "Photograph it from the Harbour Bridge",
      ],
      funFact: "Its roof is covered in over a million self-cleaning ceramic tiles.",
    },
    {
      id: "au-great-barrier-reef",
      name: "Great Barrier Reef",
      city: "Queensland",
      country: "Australia",
      description: "The world's largest coral reef system, teeming with marine life.",
      rating: 4.9,
      budgetTier: "$$$",
      budgetLabel: "AU$150–300 per person",
      bestTime: "Jun–Oct",
      highlights: [
        "Snorkel the Whitsundays' coral gardens",
        "Dive with sea turtles at Lady Elliot Island",
        "Take a scenic flight over the reef",
      ],
      funFact: "It's the only living structure on Earth visible from space.",
    },
    {
      id: "au-uluru",
      name: "Uluru",
      city: "Northern Territory",
      country: "Australia",
      description: "A monolithic red sandstone icon sacred to the Anangu people.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "AU$50–90 per person",
      bestTime: "May–Sep",
      highlights: [
        "Watch sunrise and sunset color changes",
        "Walk the base trail with an Aboriginal guide",
        "View the Field of Light art installation",
      ],
      funFact: "Uluru is estimated to be over 550 million years old.",
    },
    {
      id: "au-great-ocean-road",
      name: "Great Ocean Road",
      city: "Victoria",
      country: "Australia",
      description: "A dramatic coastal drive past cliffs, rainforest, and the Twelve Apostles.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "AU$40–80 per person",
      bestTime: "Dec–Feb",
      highlights: [
        "Stop at the Twelve Apostles lookout",
        "Spot koalas in Kennett River",
        "Surf at Bells Beach",
      ],
      funFact: "The road was built by returned WWI soldiers as the world's largest war memorial.",
    },
    {
      id: "au-bondi-beach",
      name: "Bondi Beach",
      city: "Sydney",
      country: "Australia",
      description: "A golden crescent of sand backed by a famous coastal boardwalk.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "Free",
      bestTime: "Nov–Mar",
      highlights: [
        "Walk the Bondi to Coogee coastal path",
        "Learn to surf at a local school",
        "Browse the Sunday markets",
      ],
      funFact: "Bondi's name comes from an Aboriginal word meaning 'water breaking over rocks.'",
    },
    {
      id: "au-blue-mountains",
      name: "Blue Mountains",
      city: "New South Wales",
      country: "Australia",
      description: "Eucalyptus-blue ridgelines cut by cliffs and cascading waterfalls.",
      rating: 4.6,
      budgetTier: "$",
      budgetLabel: "AU$20–40 per person",
      bestTime: "Mar–May",
      highlights: [
        "View the Three Sisters rock formation",
        "Ride the Scenic World cableway",
        "Hike to Wentworth Falls",
      ],
      funFact: "The mountains get their blue haze from eucalyptus oil in the air.",
    },
  ],
  BR: [
    {
      id: "br-christ-the-redeemer",
      name: "Christ the Redeemer",
      city: "Rio de Janeiro",
      country: "Brazil",
      description: "A towering Art Deco statue overlooking Rio from Corcovado mountain.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "R$80–150 per person",
      bestTime: "Sep–Nov",
      highlights: [
        "Ride the cog train up Corcovado",
        "Catch sunrise above the clouds",
        "View Rio's coastline from the statue's base",
      ],
      funFact: "The statue is struck by lightning several times a year and has lightning rods built in.",
    },
    {
      id: "br-iguazu-falls",
      name: "Iguazu Falls",
      city: "Paraná",
      country: "Brazil",
      description: "A thundering curtain of nearly 300 waterfalls on the Argentine border.",
      rating: 4.9,
      budgetTier: "$$",
      budgetLabel: "R$70–120 per person",
      bestTime: "May–Sep",
      highlights: [
        "Walk the Devil's Throat catwalk",
        "Take a boat ride beneath the falls",
        "View from both the Brazilian and Argentine sides",
      ],
      funFact: "Iguazu is wider than Niagara and taller than Victoria Falls.",
    },
    {
      id: "br-copacabana",
      name: "Copacabana Beach",
      city: "Rio de Janeiro",
      country: "Brazil",
      description: "A legendary curved beach alive with volleyball and sunset crowds.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "Free",
      bestTime: "Dec–Mar",
      highlights: [
        "Watch a beach volleyball match",
        "Walk the wave-patterned promenade at sunset",
        "Try fresh coconut water from a beach kiosk",
      ],
      funFact: "The beach's iconic black-and-white pavement was designed by Roberto Burle Marx.",
    },
    {
      id: "br-amazon-rainforest",
      name: "Amazon Rainforest",
      city: "Amazonas",
      country: "Brazil",
      description: "A vast, biodiverse jungle threaded by the mighty Amazon River.",
      rating: 4.7,
      budgetTier: "$$$",
      budgetLabel: "R$400–800 per person",
      bestTime: "Jun–Nov",
      highlights: [
        "Take a night wildlife-spotting canoe trip",
        "Stay in a jungle lodge near Manaus",
        "Fish for piranha on a guided tour",
      ],
      funFact: "The Amazon produces roughly 20% of the world's oxygen.",
    },
    {
      id: "br-pelourinho",
      name: "Salvador's Pelourinho",
      city: "Salvador",
      country: "Brazil",
      description: "Cobblestone streets and colonial facades pulsing with Afro-Brazilian culture.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "R$30–60 per person",
      bestTime: "Dec–Mar",
      highlights: [
        "Watch a live capoeira demonstration",
        "Explore the colorful colonial squares",
        "Visit the Church of São Francisco's gilded interior",
      ],
      funFact: "Pelourinho's historic center is a UNESCO World Heritage Site.",
    },
    {
      id: "br-fernando-de-noronha",
      name: "Fernando de Noronha",
      city: "Pernambuco",
      country: "Brazil",
      description: "A remote volcanic archipelago with pristine dive-worthy waters.",
      rating: 4.9,
      budgetTier: "$$$",
      budgetLabel: "R$600–1,000 per person",
      bestTime: "Aug–Dec",
      highlights: [
        "Dive with spinner dolphins at Baía dos Golfinhos",
        "Snorkel the Bay of Pigs",
        "Hike to Praia do Sancho, often ranked world's best beach",
      ],
      funFact: "Brazil limits daily visitor numbers to protect the archipelago's ecosystem.",
    },
  ],
  IN: [
    {
      id: "in-taj-mahal",
      name: "Taj Mahal",
      city: "Agra",
      country: "India",
      description: "An ivory-marble mausoleum built as an eternal monument to love.",
      rating: 4.9,
      budgetTier: "$$",
      budgetLabel: "₹1,100–1,300 per person",
      bestTime: "Oct–Mar",
      highlights: [
        "View it at sunrise for shifting marble colors",
        "Explore the symmetrical Mughal gardens",
        "See the reflecting pool photo spot",
      ],
      funFact: "The marble changes hue throughout the day depending on the light.",
    },
    {
      id: "in-jaipur-city-palace",
      name: "Jaipur City Palace",
      city: "Jaipur",
      country: "India",
      description: "A pink-sandstone palace complex at the heart of the Pink City.",
      rating: 4.6,
      budgetTier: "$",
      budgetLabel: "₹200–700 per person",
      bestTime: "Nov–Feb",
      highlights: [
        "See the Peacock Gate's intricate artwork",
        "Visit the royal Textile and Armoury museums",
        "Tour nearby Amber Fort by elephant or jeep",
      ],
      funFact: "The palace complex still houses the descendants of Jaipur's royal family.",
    },
    {
      id: "in-kerala-backwaters",
      name: "Kerala Backwaters",
      city: "Kerala",
      country: "India",
      description: "A tranquil network of lagoons and canals drifted by houseboats.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "₹3,000–6,000 per person",
      bestTime: "Sep–Mar",
      highlights: [
        "Cruise overnight on a traditional houseboat",
        "Watch Chinese fishing nets at work",
        "Sample a traditional sadya feast",
      ],
      funFact: "The backwaters span over 900 kilometers of interconnected canals and lagoons.",
    },
    {
      id: "in-varanasi-ghats",
      name: "Varanasi Ghats",
      city: "Varanasi",
      country: "India",
      description: "Ancient riverside steps where ritual and daily life meet the Ganges.",
      rating: 4.5,
      budgetTier: "$",
      budgetLabel: "₹500–1,500 per person",
      bestTime: "Oct–Mar",
      highlights: [
        "Watch the evening Ganga Aarti ceremony",
        "Take a sunrise boat ride on the Ganges",
        "Wander the old city's narrow lanes",
      ],
      funFact: "Varanasi is considered one of the oldest continuously inhabited cities on Earth.",
    },
    {
      id: "in-goa-beaches",
      name: "Goa Beaches",
      city: "Goa",
      country: "India",
      description: "Palm-fringed shores blending Portuguese heritage with laid-back beach life.",
      rating: 4.5,
      budgetTier: "$$",
      budgetLabel: "₹2,000–5,000 per person",
      bestTime: "Nov–Feb",
      highlights: [
        "Watch sunset at Anjuna's flea market",
        "Try Goan seafood curry beachside",
        "Explore the Portuguese architecture of Old Goa",
      ],
      funFact: "Goa was a Portuguese colony for over 450 years before joining India in 1961.",
    },
    {
      id: "in-ladakh",
      name: "Ladakh",
      city: "Jammu and Kashmir",
      country: "India",
      description: "A high-altitude desert of monasteries and mirror-still mountain lakes.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "₹4,000–8,000 per person",
      bestTime: "Jun–Sep",
      highlights: [
        "Visit Pangong Lake's shifting blue waters",
        "Tour the centuries-old Thiksey Monastery",
        "Drive the high-altitude Khardung La pass",
      ],
      funFact: "Ladakh is often called 'Little Tibet' for its shared Buddhist culture.",
    },
  ],
  EG: [
    {
      id: "eg-pyramids-of-giza",
      name: "Pyramids of Giza",
      city: "Giza",
      country: "Egypt",
      description: "The last standing wonder of the ancient world, guarded by the Sphinx.",
      rating: 4.9,
      budgetTier: "$$",
      budgetLabel: "$25–45 per person",
      bestTime: "Oct–Apr",
      highlights: [
        "See the Great Sphinx up close",
        "Ride a camel across the desert plateau",
        "Tour the Solar Boat Museum",
      ],
      funFact: "The Great Pyramid was the tallest man-made structure for nearly 3,800 years.",
    },
    {
      id: "eg-karnak-temple",
      name: "Karnak Temple",
      city: "Luxor",
      country: "Egypt",
      description: "A sprawling temple complex built up over two thousand years.",
      rating: 4.7,
      budgetTier: "$",
      budgetLabel: "$10–20 per person",
      bestTime: "Nov–Feb",
      highlights: [
        "Walk the Avenue of Sphinxes",
        "See the Great Hypostyle Hall's 134 columns",
        "Watch the evening sound and light show",
      ],
      funFact: "Karnak was built and expanded by pharaohs over roughly 2,000 years.",
    },
    {
      id: "eg-valley-of-the-kings",
      name: "Valley of the Kings",
      city: "Luxor",
      country: "Egypt",
      description: "Rock-cut royal tombs hidden beneath the western desert hills.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "$20–40 per person",
      bestTime: "Oct–Mar",
      highlights: [
        "Tour Tutankhamun's tomb",
        "See the vivid wall paintings in Ramesses VI's tomb",
        "Visit the nearby Mortuary Temple of Hatshepsut",
      ],
      funFact: "More than 60 tombs have been discovered in the valley so far.",
    },
    {
      id: "eg-red-sea-riviera",
      name: "Red Sea Riviera",
      city: "Hurghada",
      country: "Egypt",
      description: "Coral reefs and warm turquoise water framed by desert coastline.",
      rating: 4.6,
      budgetTier: "$$",
      budgetLabel: "$40–90 per person",
      bestTime: "Mar–May",
      highlights: [
        "Snorkel the reefs off Giftun Island",
        "Dive the wreck of the SS Thistlegorm",
        "Windsurf at El Gouna",
      ],
      funFact: "The Red Sea's reefs are among the most biodiverse in the world.",
    },
    {
      id: "eg-abu-simbel",
      name: "Abu Simbel Temples",
      city: "Aswan",
      country: "Egypt",
      description: "Colossal rock temples relocated stone by stone to escape the Nile floodwaters.",
      rating: 4.8,
      budgetTier: "$$$",
      budgetLabel: "$100–180 per person",
      bestTime: "Oct–Apr",
      highlights: [
        "See the twice-yearly sunrise alignment through the temple",
        "Marvel at the four colossal Ramesses II statues",
        "Tour the smaller Temple of Hathor",
      ],
      funFact: "The entire complex was moved in the 1960s to escape the rising Aswan Dam waters.",
    },
    {
      id: "eg-islamic-cairo",
      name: "Islamic Cairo",
      city: "Cairo",
      country: "Egypt",
      description: "A maze of minarets, mosques, and centuries-old bazaars.",
      rating: 4.4,
      budgetTier: "$",
      budgetLabel: "$5–15 per person",
      bestTime: "Nov–Feb",
      highlights: [
        "Explore the historic Khan el-Khalili bazaar",
        "Visit the Alabaster Mosque of Muhammad Ali",
        "Wander the medieval gates of Bab Zuweila",
      ],
      funFact: "Cairo's Islamic quarter holds one of the world's largest concentrations of medieval architecture.",
    },
  ],
  IT: [
    {
      id: "it-colosseum",
      name: "Colosseum",
      city: "Rome",
      country: "Italy",
      description: "The largest amphitheater ever built, still standing after two millennia.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "€18–35 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Tour the underground hypogeum chambers",
        "See the Roman Forum and Palatine Hill nearby",
        "Book a sunset skip-the-line tour",
      ],
      funFact: "The Colosseum could be flooded for staged naval battles in its early years.",
    },
    {
      id: "it-venice-canals",
      name: "Venice Canals",
      city: "Venice",
      country: "Italy",
      description: "A car-free city of gondolas gliding between centuries-old palazzos.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "€30–60 per person",
      bestTime: "Apr–Jun",
      highlights: [
        "Take a gondola ride through quiet back canals",
        "Visit St. Mark's Square and Basilica",
        "Explore the glass-blowing island of Murano",
      ],
      funFact: "Venice is built on more than 100 small islands linked by hundreds of bridges.",
    },
    {
      id: "it-amalfi-coast",
      name: "Amalfi Coast",
      city: "Campania",
      country: "Italy",
      description: "Pastel villages clinging to cliffs above a sparkling blue sea.",
      rating: 4.9,
      budgetTier: "$$$",
      budgetLabel: "€100–200 per person",
      bestTime: "May–Sep",
      highlights: [
        "Drive the cliffside SS163 coastal road",
        "Take a boat trip to Capri's Blue Grotto",
        "Wander Positano's stacked pastel streets",
      ],
      funFact: "The coastal road has over 1,000 curves along its roughly 30-mile stretch.",
    },
    {
      id: "it-florence-duomo",
      name: "Florence's Duomo",
      city: "Florence",
      country: "Italy",
      description: "A red-domed cathedral crowning the birthplace of the Renaissance.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "€20–30 per person",
      bestTime: "Apr–Oct",
      highlights: [
        "Climb the dome for city views",
        "See Ghiberti's Gates of Paradise doors",
        "Visit the Uffizi Gallery nearby",
      ],
      funFact: "Brunelleschi's dome remains the largest brick dome ever built.",
    },
    {
      id: "it-tuscan-countryside",
      name: "Tuscan Countryside",
      city: "Tuscany",
      country: "Italy",
      description: "Rolling vineyard hills dotted with cypress trees and hilltop towns.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "€50–100 per person",
      bestTime: "Sep–Oct",
      highlights: [
        "Tour a family-run vineyard in Chianti",
        "Climb the tower in San Gimignano",
        "Cycle between hilltop villages",
      ],
      funFact: "Tuscany's Val d'Orcia valley is a UNESCO-listed cultural landscape.",
    },
    {
      id: "it-pompeii",
      name: "Pompeii",
      city: "Naples",
      country: "Italy",
      description: "A Roman city frozen in ash since the eruption of Vesuvius in 79 AD.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "€16–22 per person",
      bestTime: "Mar–May",
      highlights: [
        "Walk the ancient Roman street grid",
        "See the plaster casts of victims",
        "Visit the well-preserved House of the Faun",
      ],
      funFact: "Pompeii was buried and preserved for over 1,600 years before its rediscovery.",
    },
  ],
  MX: [
    {
      id: "mx-chichen-itza",
      name: "Chichen Itza",
      city: "Yucatán",
      country: "Mexico",
      description: "A Mayan step-pyramid aligned with startling astronomical precision.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "$25–45 per person",
      bestTime: "Nov–Apr",
      highlights: [
        "Witness the equinox serpent-shadow illusion",
        "Climb the still-climbable pyramid at nearby Coba",
        "Swim in a cenote after the tour",
      ],
      funFact: "Clapping in front of El Castillo produces an echo resembling a sacred bird's chirp.",
    },
    {
      id: "mx-tulum-ruins",
      name: "Tulum Ruins",
      city: "Quintana Roo",
      country: "Mexico",
      description: "Clifftop Mayan ruins overlooking a turquoise Caribbean beach.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "$15–30 per person",
      bestTime: "Nov–Apr",
      highlights: [
        "Photograph the clifftop temple over turquoise water",
        "Swim at the beach right below the ruins",
        "Bike the coastal path into Tulum town",
      ],
      funFact: "Tulum was one of the last cities built and inhabited by the Maya.",
    },
    {
      id: "mx-mexico-city-historic-center",
      name: "Mexico City Historic Center",
      city: "Mexico City",
      country: "Mexico",
      description: "A UNESCO-listed plaza ringed by colonial cathedrals and Aztec ruins.",
      rating: 4.6,
      budgetTier: "$",
      budgetLabel: "Free–$10",
      bestTime: "Oct–Apr",
      highlights: [
        "Tour the Templo Mayor Aztec ruins",
        "See Diego Rivera murals in the National Palace",
        "Wander the Zócalo, one of the world's largest plazas",
      ],
      funFact: "Mexico City is slowly sinking, built atop a former Aztec lake bed.",
    },
    {
      id: "mx-cenotes-yucatan",
      name: "Cenotes of Yucatán",
      city: "Yucatán",
      country: "Mexico",
      description: "Crystal-clear sinkhole pools hiding beneath the jungle floor.",
      rating: 4.8,
      budgetTier: "$$",
      budgetLabel: "$20–50 per person",
      bestTime: "Nov–Apr",
      highlights: [
        "Snorkel the crystal waters of Cenote Dos Ojos",
        "Rappel into an open-air cenote",
        "Swim with fish in Cenote Ik Kil",
      ],
      funFact: "There are thousands of cenotes across the Yucatán, once considered sacred Maya portals.",
    },
    {
      id: "mx-copper-canyon",
      name: "Copper Canyon",
      city: "Chihuahua",
      country: "Mexico",
      description: "A network of canyons larger and deeper than the Grand Canyon.",
      rating: 4.7,
      budgetTier: "$$",
      budgetLabel: "$50–100 per person",
      bestTime: "Oct–Nov",
      highlights: [
        "Ride the El Chepe scenic railway",
        "Zip-line across the canyon at Barrancas del Cobre park",
        "Meet local Tarahumara artisans",
      ],
      funFact: "The Copper Canyon system is actually larger in total area than the Grand Canyon.",
    },
    {
      id: "mx-cabo-san-lucas",
      name: "Cabo San Lucas",
      city: "Baja California Sur",
      country: "Mexico",
      description: "Dramatic desert cliffs meeting the sea at Land's End.",
      rating: 4.5,
      budgetTier: "$$$",
      budgetLabel: "$100–250 per person",
      bestTime: "Dec–Apr",
      highlights: [
        "Boat out to see El Arco rock arch",
        "Snorkel at Chileno Bay",
        "Watch whales migrate offshore in winter",
      ],
      funFact: "Cabo sits where the Sea of Cortez meets the Pacific Ocean at Land's End.",
    },
  ],
};

export const ATTRACTIONS_BY_COUNTRY: Record<CountryCode, Attraction[]> = Object.fromEntries(
  Object.entries(RAW_ATTRACTIONS).map(([code, list]) => [code, list.map(withImage)]),
) as Record<CountryCode, Attraction[]>;

export function isSupportedCountry(code: string | null | undefined): code is CountryCode {
  return !!code && code in ATTRACTIONS_BY_COUNTRY;
}

export function attractionsFor(code: CountryCode): Attraction[] {
  return ATTRACTIONS_BY_COUNTRY[code];
}
